<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="otywin-17" name="com.formsdirectinc.qa.app.registration.RegistrationTest" tests="4" failures="0" timestamp="23 Sep 2016 11:22:38 GMT" time="0.435" errors="1">
  <testcase name="testCase1" time="0.128" classname="com.formsdirectinc.qa.app.registration.RegistrationTest"/>
  <testcase name="testCase2" time="0.011" classname="com.formsdirectinc.qa.app.registration.RegistrationTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.formsdirectinc.qa.app.registration.testcase.Footer.verifyRegistrationDisclaimer(Footer.java:42)
	at com.formsdirectinc.qa.app.registration.RegistrationTest.testCase2(RegistrationTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase4" time="0.248" classname="com.formsdirectinc.qa.app.registration.RegistrationTest"/>
  <testcase name="testCase3" time="0.048" classname="com.formsdirectinc.qa.app.registration.RegistrationTest"/>
</testsuite> <!-- com.formsdirectinc.qa.app.registration.RegistrationTest -->
